name: "Build and Test"

on:
  workflow_call:
  push:
    branches-ignore:
      - main

jobs:
  setup-jdk:
    name: "Setup JDK"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Inspect setup
        run: ls -a
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    needs: setup-jdk
    steps:
      - uses: actions/checkout@v3
      - run: sbt compile
      - name: Inspect build
        run: ls -a
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: sbt test
