name: "CI"

on: push

jobs:
  setup-jdk:
    name: "Setup JDK"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    needs: setup-jdk
    steps:
      - uses: actions/checkout@v3
      - run: sbt compile
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: sbt test
  add-release:
    name: "Add release"
    runs-on: "ubuntu-latest"
    needs: test
    if: github.ref_type == tag
    steps:
      - uses: actions/checkout@v3
      - run: sbt assembly
      - run: mkdir release && cp target/ptp-latest.jar release/ptp-${{ github.ref_name }}.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: target/*.jar
