name: "Pre-release"

on: 
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: "Build and Test"
    uses: AlexB02/pseudo-tools/.github/workflows/build-test.yaml@main
  
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - run: sbt assembly
      - run: mkdir release && cp target/ptp-latest.jar release/ptp-latest.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: release/*.jar
          automatic_release_tag: latest
